blank_issues_enabled: false
contact_links:
  - name: ğŸ’¡ Feature Request
    url: https://github.com/withastro/starlight/discussions/new?category=feature-requests
    about: Suggest an improvement youâ€™d like to see added to Starlight
  - name: ğŸ‘¾ Chat
    url: https://astro.build/chat
    about: Our Discord server is active, come join us!
  - name: ğŸ’ Support
    url: https://astro.build/chat
    about: 'This issue tracker is not for support questions. Join us on Discord for assistance!'
