name: File icons generator

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  icons:
    name: Generate file icons
    if: github.repository_owner == 'withastro'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup PNPM
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      - name: Setup Node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 18.20.8
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm i

      - name: Run file icons generator
        run: pnpm build
        working-directory: packages/file-icons-generator

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          branch: ci/file-icons
          token: ${{ secrets.FREDKBOT_GITHUB_TOKEN }}
          commit-message: 'ci: update file icons'
          title: 'ci: update file icons'
          body: |
            This PR is auto-generated by a GitHub action to update the file icons and file tree definitions available in Starlight.
