name: Lunaria

on:
  # Trigger the workflow every time a pull request is opened or synchronized at the target `main` branch
  pull_request_target:
    types: [opened, synchronize]
    branches: [main]
    paths:
      - 'docs/**'

# Allow this job to clone the repository and comment on the pull request
permissions:
  contents: read
  pull-requests: write

jobs:
  lunaria-overview:
    name: Generate Lunaria Overview
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          # Necessary for Lunaria to work properly
          # Makes the action clone the entire git history
          fetch-depth: 0

      - name: Setup PNPM
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      - name: Setup Node
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 20.19.4
          cache: pnpm

      - name: Install dependencies
        run: pnpm install
        shell: bash

      - name: Generate Lunaria Overview
        uses: yanthomasdev/lunaria-action@06ad5ab2704d030708baf3b279ca0446b418e853 # v0.1.0
        with:
          token: ${{ secrets.FREDKBOT_GITHUB_TOKEN }}
          working-directory: docs
