name: Size Limit

on:
  pull_request:
    branches: [main]

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 22

jobs:
  # This basic check runs size-limit for the current branch.
  # It will fail if the branch pushes the size over the specified budget.
  size-limit-basic:
    if: ${{ github.event.pull_request.head.repo.full_name != 'withastro/starlight' }}
    name: Check build output is within performance budget (forks)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - name: Setup Node
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
      - run: pnpm i
      - run: 'pnpm build:examples'
      - run: pnpm size

  # This check cannot run in forks, so is only run for PRs from this repo.
  # It will run size-limit for both `main` and the PR branch and comment in the PR with changes.
  size-limit:
    if: ${{ github.event.pull_request.head.repo.full_name == 'withastro/starlight' }}
    name: Check build output is within performance budget
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - name: Setup Node
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
      - name: Run size-limit
        uses: andresz1/size-limit-action@94bc357df29c36c8f8d50ea497c3e225c3c95d1d # v1.8.0
        with:
          github_token: ${{ secrets.FREDKBOT_GITHUB_TOKEN }}
          build_script: 'build:examples'
          package_manager: pnpm
